### ISSUE TITLE
B6: Github Profile Fetcher

### ISSUE THREAD

**Issue by SakshamDevelops** [SakshamDevelops/Frontend-101#12]
fetch()
.then
.then
.catch

https://sakshamdevelops.github.io/Frontend-101/B/B6/B6.html

**Comment by NidheeshJain** [comment]
Though the main functionality is intact and really well put up, the UI could be improved.
1. The issue I see is that gifs are not well-cropped rn, which leads to an overflow in the x-direction. This could be avoided by cropping the gifs nicely.
2. In mobile view the aspect ratios of background images are pretty skewed. Check how to maintain the aspect ratio of the background image on any element sizes.
3. Though removing the submit button gives a clean UI. On mobile, it becomes a bit inconvenient for the user to submit the GitHub username. A submit button could be added to improve the accessibility. This is optional.

**Comment by SakshamDevelops** [comment]
I fixed it, you can check it now
