### ISSUE TITLE
B7: 2048 Game Time

### ISSUE THREAD

**Issue by SakshamDevelops** [SakshamDevelops/Frontend-101#13]
https://sakshamdevelops.github.io/Frontend-101/B/B7/B7.html

Jaan nikal Gayi

🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺
🥺
🥺
🥺
🥺🥺🥺🥺🥺🥺🥺🥺
🥺
🥺
🥺
🥺

**Comment by NidheeshJain** [comment]
Noice!
