### ISSUE TITLE
A5 - DVM Logo Reveal

### ISSUE THREAD

**Issue by SakshamDevelops** [SakshamDevelops/Frontend-101#4]
https://sakshamdevelops.github.io/Frontend-101/A/A5/A5.html

Dynamically setting

stroke-dashoffset
stroke-dasharray

using JS to determine length of SVG

**Comment by mananag** [comment]
The SVG is good but the stroke transition is not smooth plus its different from the original one. Also the color transition is also wrong.

**Comment by SakshamDevelops** [comment]
I didn't replicate the old transitions; instead, I tried to make it look better, so that's why I changed those.
Can you elaborate on what do we mean by "not smooth" here?

**Comment by NidheeshJain** [comment]
I think @mananag meant that you should have applied some easing effects to the animations, instead of linear as they are now. But ig, you got the crux of activity, so closing the issue.
You may update the animation effects later on.
