### ISSUE TITLE
B1:(Canvas API) Making clock with Canvas API

### ISSUE THREAD

**Issue by SakshamDevelops** [SakshamDevelops/Frontend-101#6]
https://sakshamdevelops.github.io/Frontend-101/B/B1%20Canvas/B1C.html

ctx.beginPath()
ctx.arc()
ctx.moveTo()
ctx.lineTo()
ctx.closePath();

time using new date()

using sin and cos for x,y co-ordinates of ctx.lineTo()

setInterval

**Comment by mananag** [comment]
Good
