### ISSUE TITLE
B1: (HTML,CSS,JS) Clock

### ISSUE THREAD

**Issue by SakshamDevelops** [SakshamDevelops/Frontend-101#7]
https://sakshamdevelops.github.io/Frontend-101/B/B1%20JS/B1.html

dynamically setting transform: rotate(x deg) value to make hands rotate
using new date()

**Comment by mananag** [comment]
The starting transition of the minute is looking weird. Try to fix it. Otherwise looking good

**Comment by SakshamDevelops** [comment]
I changed it. Is it ok now?

**Comment by SakshamDevelops** [comment]
??

**Comment by NidheeshJain** [comment]
Looks good to me. Closing the issue.

A general suggestion: Don't display the canvas until it's fully initialized. This would help prevent the jumpy thing which happens at the start. This can be done by setting default display: none; and then upon complete initialization setting display: block | flex etc.
