### ISSUE TITLE
B3: To-Do List

### ISSUE THREAD

**Issue by SakshamDevelops** [SakshamDevelops/Frontend-101#9]
https://sakshamdevelops.github.io/Frontend-101/B/B3/B3.html

using 
localstorage.getItem()
JSON.stringify
JSON.parse
refreshing all items after user presses + icon 
arr.splice to remove items

**Comment by mananag** [comment]
We are able to generate an empty task. Fix it. Otherwise good work on this

**Comment by SakshamDevelops** [comment]
I fixed it, you can check it now

**Comment by mananag** [comment]
Yup now its perfect. Also great job on design 🚀

**Comment by SakshamDevelops** [comment]
Thanks
